environmentVariables:
  loglevel: info
  gormLogLevel: 1
mysql:
  xcamera: #业务类型
    master: #主库
      address: rm-wz9i2o05w5827f97s.mysql.rds.aliyuncs.com:3306
      name: xcamera
      user: test_admin
      password: Sway_video
    slaves: #从库
      - address: rm-wz9i2o05w5827f97s.mysql.rds.aliyuncs.com:3306
        name: xcamera
        user: test_admin
        password: Sway_video
      - address: rm-wz9i2o05w5827f97s.mysql.rds.aliyuncs.com:3306
        name: xcamera
        user: test_admin
        password: Sway_video
redis:
  first: #主从DB
    address: r-wz9r4olm9qm2clzuvw.redis.rds.aliyuncs.com:6379
    password: XcameraTest0509
  second: #集群版DB
    address: r-wz9r4olm9qm2clzuvw.redis.rds.aliyuncs.com:6379
    password: XcameraTest0509

elastic:
  shake: #摇一摇
    url: http://es-cn-zvp269ei50023flho.elasticsearch.aliyuncs.com:9200/
    username: elastic
    password: 115b-a00c-4358-9237-9051
rpc:
  data_center:
    - 10.29.0.203:10006
kafka:
  sensor:
    address:
      - 172.18.250.35:9092
      - 172.18.250.36:9092
      - 172.18.250.37:9092
    topic: test-sa
